target-version = "py312" 
line-length = 120

exclude = [
  ".venv",
  ".venv_elt",
  ".venv_train",
  ".venv_train_dev",
  ".venv_deploy",
  ".repo",
  ".venv_auth",
  "__pycache__",
  "ELT",
]

[lint]
select = ["E4", "E7", "E9", "F", "B", "I", "UP", "RUF"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true



