apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: postgres-cluster-manual-20260404071406-142452
  namespace: default
spec:
  method: barmanObjectStore
  cluster:
    name: postgres-cluster
