apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: postgres-cluster-manual-20260409151701-92075
  namespace: default
spec:
  method: barmanObjectStore
  cluster:
    name: postgres-cluster
