apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-cluster-latest-restore-validate-110697-backup
  namespace: default
spec:
  cluster:
    name: postgres-cluster-latest-restore-validate-110697
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: barmanObjectStore
