apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mlflow-pdb
  namespace: mlflow
  labels:
    app.kubernetes.io/name: mlflow
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow
      app.kubernetes.io/component: server
