apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-sa
  namespace: inference
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/managed-by: auth-service
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: auth-svc
automountServiceAccountToken: false
