apiVersion: v1
kind: ConfigMap
metadata:
  name: iceberg-rest-conf
  namespace: default
data:
  gravitino-iceberg-rest-server.conf: |
    gravitino.iceberg-rest.host=0.0.0.0
    gravitino.iceberg-rest.httpPort=9001
    gravitino.iceberg-rest.catalog-config-provider=static-config-provider
    gravitino.iceberg-rest.catalog-backend=jdbc
    gravitino.iceberg-rest.catalog-backend-name=jdbc
    gravitino.iceberg-rest.jdbc-initialize=true
    gravitino.iceberg-rest.jdbc.schema-version=V1
