apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg-rest
  namespace: default
  labels:
    app: iceberg-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg-rest
  template:
    metadata:
      labels:
        app: iceberg-rest
    spec:
      serviceAccountName: iceberg-rest-sa
      securityContext:
        runAsNonRoot: true
      containers:
        - name: grav
          image: ghcr.io/athithya-sakthivel/iceberg-rest-gravitino-postgres@sha256:bb2ac1c0328a94b65834aa0bae9e863baf8aaee7557810e7b79c71f3537d13ea
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9001
          env:
            - name: ICEBERG_REST_AUTH_TYPE
              value: "basic"
            - name: ICEBERG_REST_USER
              valueFrom:
                secretKeyRef:
                  name: iceberg-rest-auth
                  key: user
            - name: ICEBERG_REST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iceberg-rest-auth
                  key: password
            - name: GRAVITINO_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: iceberg-storage-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: GRAVITINO_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: iceberg-storage-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: GRAVITINO_S3_REGION
              value: "ap-south-1"
            - name: GRAVITINO_S3_ENDPOINT
              value: ""
            - name: GRAVITINO_S3_PATH_STYLE_ACCESS
              value: "false"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
