apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: inference
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/component: tunnel-config
data:
  config.yaml: "tunnel: tabular-api-tunnel\ningress:\n- hostname: auth.athithya.site\n  service: http://auth-svc.inference.svc.cluster.local:80\n\
    - hostname: predict.athithya.site\n  service: http://tabular-inference-serve-svc.inference.svc.cluster.local:8000\n- service:\
    \ http_status:404\n"
